memphisx/netcheck-api

src/main/java/com/bompotis/netcheck/api/model/DomainModel.java, src/main/java/com/bompotis/netcheck/api/model/assembler/DomainModelAssembler.java, src/main/java/com/bompotis/netcheck/data/repository/DomainCheckRepository.java, src/main/java/com/bompotis/netcheck/service/DomainService.java, src/main/java/com/bompotis/netcheck/service/dto/DomainDto.java, src/main/java/com/bompotis/netcheck/service/dto/PaginatedDomainsDto.java
resolves #34  Always return results ordered by created_at (newer entries first)
resolves #35  fetch last check per domain on GET /domains
=> issue-35: fetch last check per domain on GET /domains

src/main/java/com/bompotis/netcheck/data/entity/AbstractTimestampable.java, src/main/java/com/bompotis/netcheck/data/entity/AbstractTimestampablePersistable.java, src/main/java/com/bompotis/netcheck/data/entity/CertificateEntity.java, src/main/java/com/bompotis/netcheck/data/entity/DomainCheckEntity.java, src/main/java/com/bompotis/netcheck/data/entity/DomainEntity.java, src/main/java/com/bompotis/netcheck/data/entity/ProtocolCheckEntity.java, src/main/java/com/bompotis/netcheck/scheduler/batch/DomainEntryProcessor.java, src/main/java/com/bompotis/netcheck/service/DomainService.java
=> issue-22: Replace setters with constructors/builders to all JPA entities

pom.xml, src/main/java/com/bompotis/netcheck/api/controller/DomainsController.java, src/main/java/com/bompotis/netcheck/api/model/CertificateModel.java, src/main/java/com/bompotis/netcheck/api/model/DomainCheckModel.java, src/main/java/com/bompotis/netcheck/api/model/HttpCheckModel.java, src/main/java/com/bompotis/netcheck/api/model/assembler/DomainCheckModelAssembler.java, src/main/java/com/bompotis/netcheck/api/model/assembler/HttpCheckModelAssembler.java, src/main/java/com/bompotis/netcheck/data/entity/ProtocolCheckEntity.java, src/main/java/com/bompotis/netcheck/service/DomainService.java, src/main/java/com/bompotis/netcheck/service/dto/HttpCheckDto.java, src/main/java/com/bompotis/netcheck/service/dto/HttpsCheckDto.java, src/main/resources/META-INF/additional-spring-configuration-metadata.json, src/main/resources/application.yaml, src/test/resources/application.yaml
resolves #38  
resolves #42  
resolves #45  
resolves #46
=> Issues #38 #42 #45 #46

src/main/java/com/bompotis/netcheck/api/controller/DomainsController.java, src/main/java/com/bompotis/netcheck/api/model/HttpCheckModel.java, src/main/java/com/bompotis/netcheck/api/model/StateModel.java, src/main/java/com/bompotis/netcheck/api/model/assembler/DomainCheckModelAssembler.java, src/main/java/com/bompotis/netcheck/api/model/assembler/DomainModelAssembler.java, src/main/java/com/bompotis/netcheck/api/model/assembler/StateModelAssembler.java, src/main/java/com/bompotis/netcheck/data/entity/AbstractTimestampablePersistable.java, src/main/java/com/bompotis/netcheck/data/entity/CertificateEntity.java, src/main/java/com/bompotis/netcheck/data/entity/DomainCheckEntity.java, src/main/java/com/bompotis/netcheck/data/entity/DomainEntity.java, src/main/java/com/bompotis/netcheck/data/entity/ProtocolCheckEntity.java, src/main/java/com/bompotis/netcheck/data/repository/DomainCheckRepository.java, src/main/java/com/bompotis/netcheck/scheduler/batch/DomainEntryProcessor.java, src/main/java/com/bompotis/netcheck/service/DomainService.java, src/main/java/com/bompotis/netcheck/service/dto/HttpCheckDto.java, src/main/java/com/bompotis/netcheck/service/dto/StateDto.java
=> Issue 29 & 48 + Endpoint exposing states

src/main/java/com/bompotis/netcheck/api/model/DomainCheckModel.java, src/main/java/com/bompotis/netcheck/api/model/assembler/DomainCheckModelAssembler.java, src/main/java/com/bompotis/netcheck/service/DomainService.java, src/main/java/com/bompotis/netcheck/service/dto/DomainCheckDto.java
=> issue-58: Introduce Monitored property to domain checks

src/main/java/com/bompotis/netcheck/api/controller/DomainsController.java, src/main/java/com/bompotis/netcheck/api/model/assembler/DomainModelAssembler.java, src/main/java/com/bompotis/netcheck/api/model/assembler/PaginatedRepresentationModelAssemblerSupport.java, src/main/java/com/bompotis/netcheck/api/model/assembler/StateModelAssembler.java, src/main/java/com/bompotis/netcheck/data/entity/ProtocolCheckEntity.java, src/main/java/com/bompotis/netcheck/scheduler/batch/DomainEntryProcessor.java, src/main/java/com/bompotis/netcheck/service/DomainService.java, src/main/java/com/bompotis/netcheck/service/dto/AbstractHttpChecker.java, src/main/java/com/bompotis/netcheck/service/dto/DomainCheckDto.java, src/main/java/com/bompotis/netcheck/service/dto/HttpCheckDto.java
resolves #57 
resolves #55 
resolves #54 
resolves #53
=> Handling of domains with invalid certs. 5XX empty responses handling. Handling server connection drops.

src/main/java/com/bompotis/netcheck/api/controller/DomainsController.java, src/main/java/com/bompotis/netcheck/api/model/DomainModel.java, src/main/java/com/bompotis/netcheck/api/model/assembler/DomainModelAssembler.java, src/main/java/com/bompotis/netcheck/scheduler/batch/BatchConfiguration.java, src/main/java/com/bompotis/netcheck/scheduler/batch/writer/NotificationItemWriter.java, src/main/java/com/bompotis/netcheck/scheduler/task/CheckDomainTask.java, src/main/java/com/bompotis/netcheck/service/DomainService.java, src/main/java/com/bompotis/netcheck/service/dto/DomainDto.java
=> issue51: Multiple check schedulers depending on the frequency

pom.xml, src/main/java/com/bompotis/netcheck/scheduler/batch/BatchConfiguration.java, src/main/java/com/bompotis/netcheck/scheduler/batch/notification/NotificationDto.java, src/main/java/com/bompotis/netcheck/scheduler/batch/notification/NotificationService.java, src/main/java/com/bompotis/netcheck/scheduler/batch/notification/PushoverService.java, src/main/java/com/bompotis/netcheck/scheduler/batch/processor/DomainCheckProcessor.java, src/main/java/com/bompotis/netcheck/scheduler/batch/writer/NotificationItemWriter.java, src/main/resources/META-INF/additional-spring-configuration-metadata.json
=> issue #63: Initial support for notifications & Pushover implementation

src/main/java/com/bompotis/netcheck/api/model/DomainModel.java, src/main/java/com/bompotis/netcheck/data/entity/DomainCheckEntity.java, src/main/java/com/bompotis/netcheck/data/entity/DomainMetricEntity.java
=> Fixes for issues #68 and #69

src/main/java/com/bompotis/netcheck/api/controller/DomainsController.java, src/main/java/com/bompotis/netcheck/api/model/StateModel.java, src/main/java/com/bompotis/netcheck/api/model/assembler/StateModelAssembler.java, src/main/java/com/bompotis/netcheck/data/repository/DomainCheckRepository.java, src/main/java/com/bompotis/netcheck/service/DomainService.java, src/main/java/com/bompotis/netcheck/service/dto/StateDto.java
=> issue-72: Fix duplicate states,wrong state change reasons+duration field

.circleci/config.yml
=> issue-74: Deploy maven package to github along with each release

pom.xml, src/main/resources/application.yaml
=> issues #80 & #79 - Restrict enabled actuators. Include additional info

Dockerfile, pom.xml, src/main/resources/application.yaml
=> issue-76: Optimizing Docker image generation and execution

Dockerfile
=> issue-83: Added curl package to fix unhealthy docker status

src/main/java/com/bompotis/netcheck/NetcheckApplication.java, src/main/java/com/bompotis/netcheck/api/controller/CheckController.java, src/main/java/com/bompotis/netcheck/api/controller/DomainsController.java, src/main/java/com/bompotis/netcheck/api/model/StateModel.java, src/main/java/com/bompotis/netcheck/data/entity/DomainCheckEntity.java, src/main/java/com/bompotis/netcheck/data/repository/DomainCheckRepository.java, src/main/java/com/bompotis/netcheck/data/repository/DomainRepository.java, src/main/java/com/bompotis/netcheck/scheduler/batch/BatchConfiguration.java, src/main/java/com/bompotis/netcheck/scheduler/batch/notification/NotificationDto.java, src/main/java/com/bompotis/netcheck/scheduler/batch/notification/PushoverService.java, src/main/java/com/bompotis/netcheck/scheduler/batch/notification/config/PushoverConfig.java, src/main/java/com/bompotis/netcheck/scheduler/batch/processor/DomainMetricProcessor.java, src/main/java/com/bompotis/netcheck/scheduler/batch/reader/OldDomainCheckItemReader.java, src/main/java/com/bompotis/netcheck/scheduler/batch/writer/NotificationItemWriter.java, src/main/java/com/bompotis/netcheck/scheduler/task/CheckDomainTask.java, src/main/java/com/bompotis/netcheck/service/AbstractService.java, src/main/java/com/bompotis/netcheck/service/DomainService.java, src/main/java/com/bompotis/netcheck/service/MetricService.java, src/main/java/com/bompotis/netcheck/service/dto/AbstractHttpChecker.java, src/main/java/com/bompotis/netcheck/service/dto/StateDto.java, src/main/resources/META-INF/additional-spring-configuration-metadata.json, src/main/resources/application.yaml
resolves #78 
resolves #33 
resolves #86 
resolves #64 
resolves #77
=> issues #78 #33 #86 #64 #77 : Refactored db, schedulers, notifications and endpoints

pom.xml, src/main/java/com/bompotis/netcheck/NetcheckApplication.java, src/main/java/com/bompotis/netcheck/api/controller/CheckController.java, src/main/java/com/bompotis/netcheck/api/controller/DomainsController.java, src/main/resources/application.yaml
=> issue-4: OpenAPI doc generation

src/main/java/com/bompotis/netcheck/api/model/DomainModel.java, src/main/java/com/bompotis/netcheck/service/dto/AbstractHttpChecker.java
=> issue-91: Handling 307 + rename lastDomainCheckModel prop to lastChecks

.github/workflows/test-and-release.yaml, amd64.openj9.Dockerfile, test-depedancies.docker-compose.yml
=> Issue #93: Multiarch docker images

.github/workflows/test-and-release.yaml, README.md
=> issue-3: Minor changes

.github/workflows/test-and-release.yaml, amd64.openj9.withUI.Dockerfile, traefik.docker-compose.yml, withUI.Dockerfile
=> issue-106: Docker images with ui bundled to the backend + traefik docker compose example

README.md, amd64.openj9.withUI.Dockerfile, src/main/java/com/bompotis/netcheck/service/dto/AbstractHttpChecker.java, withUI.Dockerfile
=> issue-114: Fix NoRouteToHostEception handling + Dockerfile optimizations

amd64.openj9.withUI.Dockerfile, pom.xml, src/main/java/com/bompotis/netcheck/data/entity/DomainEntity.java, src/main/java/com/bompotis/netcheck/service/DomainService.java, src/main/java/com/bompotis/netcheck/service/dto/AbstractHttpChecker.java, withUI.Dockerfile
=> issue-138: Bug fixing and bump frontend for combined docker images
